package main

import (
	game "github.com/garydunkerley/randomGO/internal/game"
	"math"

	_ "image/png"
	"log"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

// declaring the gameState struct
var state game.boardState

// some global parameters

var isRandom bool

// declaring graphical assets

var wood *ebiten.Image
var graph *ebiten.Image
var whiteStone *ebiten.Image
var blackStone *ebiten.Image

// numeric variables we may wish to fix

// stoneRadius will tell us how large our stone assets should be
var stoneRadius float64

// buttonRadius should be computed using geometric information
// about the graph embedding. It should be at least as big as the// pciture of the stone, but less than half the width of the shortest distance between two nodes in our graph.

var buttonRadius float64

// some values to be used for rescaling the graph

func init() {
	var err error

	state, isRandom = game.EbitenRandomGame(300, 10)
	game.MakeEbitenGraphAsset(state.GoGraph, isRandom)

	wood, _, err = ebitenutil.NewImageFromFile("assets/woodgrain3.png")

	graph, _, err = ebitenutil.NewImageFromFile("assets/temporary/board.png")
	whiteStone, _, err = ebitenutil.NewImageFromFile("assets/go_stone_white.png")
	blackStone, _, err = ebitenutil.NewImageFromFile("assets/go_stone_black.png")

	if err != nil {
		log.Fatal(err)
	}

}

type Game struct{}

// TODO:
// Figure out how to pipe in the board generated by graphviz
// as well as the geometric data.
// I think we can use graphviz to output the raw .png file for the board lines.
// To get the geometric data, we're going to need to pipe in the // dot data.

// We also need to figure out how to get this to interface with
// the backend.

func (g *Game) Update() error {
	return nil
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	width, height := wood.Size()
	return width + 500, height
}

func (g *Game) Draw(screen *ebiten.Image) {

	// draws the wood for the board
	screen.DrawImage(wood, nil)

	// adds the graph produced by graphviz
	// with suitable translation and rescaling
	// to ensure that it is centered

	gWidth, gHeight := graph.Size()
	wWidth, wHeight := wood.Size()
	rescale := 0.95

	rWidth := rescale * float64(wWidth) / float64(gWidth)
	rHeight := rescale * float64(wHeight) / float64(gHeight)

	tWidth := ((1 - rescale) * float64(wWidth)) / 2
	tHeight := ((1 - rescale) * float64(wHeight)) / 2

	graphPos := &ebiten.DrawImageOptions{}
	graphPos.GeoM.Scale(rWidth, rHeight)
	graphPos.GeoM.Translate(tWidth, tHeight)

	screen.DrawImage(graph, graphPos)
}

// this struct will track the stone objects as they occur in the game

type ebitenNode struct {
	picture    *ebiten.Image
	id         int
	xPos, yPos float64
}

/*
func isNodeClicked(x, y int, ebitenNodeMap map[int]ebitenNode) (int, bool) {
	for _, node := range ebitenNodeMap {
		if math.Sqrt(math.Pow(float64(x)-node.xPos, 2)+math.Pow(float64(y)-node.yPos, 2)) <= buttonRadius {
			if ebiten.IsMouseButtonPressed(ebiten.MouseButtonLeft) {
				return node.id, true
			}
		}
	}

	return -1, false
}

func getPlayerInput() {

	return
}

func placeStone() {
	if CursorPosition() ==

}

func update(screen *ebiten.Image) error {
	return

}
*/

func main() {

	ebiten.SetWindowSize(1000, 1000)
	ebiten.SetWindowTitle("randomGO: Randomly generated Go boards")
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
	game.state.EbitenRunGame(isRandom)
}
